[package]
name = "fhe_fixed"
version = "0.1.0"
edition = "2024"

[dependencies]
tfhe = { path = "../tfhe-rs/tfhe", version = "~1.1.0-alpha.0", features = ["boolean", "shortint", "integer", "fixed", "noise-asserts"] }
fixed = "1.29"
typenum = "1.18.0"